[tool.poetry]
name = "mycoolpackage"
version = "0.1.1"
description = ""
authors = ["Kameron Ingrando <kameron.ingrando@uta.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
